#ifndef CONTROL_BUTTON_ENV
#define CONTROL_BUTTON_ENV
#define LED_BUTTON_PIN 19
#define BUTTON_PIN 4
#define PRESS_TIME 10000
#define DOUBLE_CLICK_DURATION 200
#define BUTTON_CORE_CPU 0

#define LEDC_CHANNEL_0 0
#define LEDC_TIMER_8_BIT 8
#define LEDC_BASE_FREQ 5000

#define BLINK_CYCLE 500   // ms
#define FADE_FAST_FACTOR 5   // ms
#define FADE_SLOW_FACTOR 10   // ms
#endif